-- V1__create_table_clientes.sql (H2 - ambiente de desenvolvimento e testes)

CREATE TABLE clientes (
    id               BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(100)    NOT NULL,
    cpf              CHAR(11)        NOT NULL,
    email            VARCHAR(150)    NOT NULL,
    telefone         VARCHAR(11),
    data_nascimento  DATE            NOT NULL,
    endereco         VARCHAR(255),
    cidade           VARCHAR(100),
    estado           CHAR(2),
    cep              CHAR(8),
    data_cadastro    TIMESTAMP       NOT NULL DEFAULT NOW(),
    data_atualizacao TIMESTAMP,

    CONSTRAINT uq_clientes_cpf   UNIQUE (cpf),
    CONSTRAINT uq_clientes_email UNIQUE (email)
);

CREATE INDEX idx_clientes_nome  ON clientes (nome);
CREATE INDEX idx_clientes_email ON clientes (email);
CREATE INDEX idx_clientes_cpf   ON clientes (cpf);
